import type {Option} from 'react-querybuilder';

export const regions: Option[] = [
    {name: 'AD', label: 'Andorra'},
    {name: 'AE', label: 'United Arab Emirates'},
    {name: 'AF', label: 'Afghanistan'},
    {name: 'AG', label: 'Antigua and Barbuda'},
    {name: 'AI', label: 'Anguilla'},
    {name: 'AL', label: 'Albania'},
    {name: 'AM', label: 'Armenia'},
    {name: 'AN', label: 'Netherlands Antilles'},
    {name: 'AO', label: 'Angola'},
    {name: 'AQ', label: 'Antarctica'},
    {name: 'AR', label: 'Argentina'},
    {name: 'AS', label: 'American Samoa'},
    {name: 'AT', label: 'Austria'},
    {name: 'AU', label: 'Australia'},
    {name: 'AW', label: 'Aruba'},
    {name: 'AZ', label: 'Azerbaijan'},
    {name: 'BA', label: 'Bosnia and Herzegovina'},
    {name: 'BB', label: 'Barbados'},
    {name: 'BD', label: 'Bangladesh'},
    {name: 'BE', label: 'Belgium'},
    {name: 'BF', label: 'Burkina Faso'},
    {name: 'BG', label: 'Bulgaria'},
    {name: 'BH', label: 'Bahrain'},
    {name: 'BI', label: 'Burundi'},
    {name: 'BJ', label: 'Benin'},
    {name: 'BM', label: 'Bermuda'},
    {name: 'BN', label: 'Brunei Darussalam'},
    {name: 'BO', label: 'Bolivia'},
    {name: 'BR', label: 'Brazil'},
    {name: 'BS', label: 'Bahamas'},
    {name: 'BT', label: 'Bhutan'},
    {name: 'BUMM', label: 'Burma'},
    {name: 'BW', label: 'Botswana'},
    {name: 'BY', label: 'Belarus'},
    {name: 'BZ', label: 'Belize'},
    {name: 'CA', label: 'Canada'},
    {name: 'CD', label: 'Democratic Republic of the Congo'},
    {name: 'CF', label: 'Central African Republic'},
    {name: 'CG', label: 'Congo'},
    {name: 'CH', label: 'Switzerland'},
    {name: 'CI', label: 'Ivory Coast'},
    {name: 'CK', label: 'Cook Islands'},
    {name: 'CL', label: 'Chile'},
    {name: 'CM', label: 'Cameroon'},
    {name: 'CN', label: 'China'},
    {name: 'CO', label: 'Colombia'},
    {name: 'CR', label: 'Costa Rica'},
    {name: 'CSHH', label: 'Czechoslovakia'},
    {name: 'CSXX', label: 'Czechoslovakia'},
    {name: 'CU', label: 'Cuba'},
    {name: 'CV', label: 'Cape Verde'},
    {name: 'CW', label: 'Curacao'},
    {name: 'CY', label: 'Cyprus'},
    {name: 'CZ', label: 'Czech Republic'},
    {name: 'DDDE', label: 'East Germany'},
    {name: 'DE', label: 'Germany'},
    {name: 'DJ', label: 'Djibouti'},
    {name: 'DK', label: 'Denmark'},
    {name: 'DM', label: 'Dominica'},
    {name: 'DO', label: 'Dominican Republic'},
    {name: 'DZ', label: 'Algeria'},
    {name: 'EC', label: 'Ecuador'},
    {name: 'EE', label: 'Estonia'},
    {name: 'EG', label: 'Egypt'},
    {name: 'EH', label: 'Western Sahara'},
    {name: 'ER', label: 'Eritrea'},
    {name: 'ES', label: 'Spain'},
    {name: 'ET', label: 'Ethiopia'},
    {name: 'FI', label: 'Finland'},
    {name: 'FJ', label: 'Fiji'},
    {name: 'FO', label: 'Faroe Islands'},
    {name: 'FR', label: 'France'},
    {name: 'GA', label: 'Gabon'},
    {name: 'GB', label: 'United Kingdom'},
    {name: 'GD', label: 'Grenada'},
    {name: 'GE', label: 'Georgia'},
    {name: 'GF', label: 'French Guiana'},
    {name: 'GH', label: 'Ghana'},
    {name: 'GI', label: 'Gibraltar'},
    {name: 'GL', label: 'Greenland'},
    {name: 'GM', label: 'Gambia'},
    {name: 'GN', label: 'Guinea'},
    {name: 'GP', label: 'Guadeloupe'},
    {name: 'GQ', label: 'Equatorial Guinea'},
    {name: 'GR', label: 'Greece'},
    {name: 'GT', label: 'Guatemala'},
    {name: 'GU', label: 'Guam'},
    {name: 'GW', label: 'Guinea-Bissau'},
    {name: 'GY', label: 'Guyana'},
    {name: 'HK', label: 'Hong Kong'},
    {name: 'HN', label: 'Honduras'},
    {name: 'HR', label: 'Croatia'},
    {name: 'HT', label: 'Haiti'},
    {name: 'HU', label: 'Hungary'},
    {name: 'ID', label: 'Indonesia'},
    {name: 'IE', label: 'Ireland'},
    {name: 'IL', label: 'Israel'},
    {name: 'IM', label: 'Isle of Man'},
    {name: 'IN', label: 'India'},
    {name: 'IQ', label: 'Iraq'},
    {name: 'IR', label: 'Iran'},
    {name: 'IS', label: 'Iceland'},
    {name: 'IT', label: 'Italy'},
    {name: 'JM', label: 'Jamaica'},
    {name: 'JO', label: 'Jordan'},
    {name: 'JP', label: 'Japan'},
    {name: 'KE', label: 'Kenya'},
    {name: 'KG', label: 'Kyrgyzstan'},
    {name: 'KH', label: 'Cambodia'},
    {name: 'KI', label: 'Kiribati'},
    {name: 'KM', label: 'Comoros'},
    {name: 'KN', label: 'Saint Kitts and Nevis'},
    {name: 'KP', label: 'North Korea'},
    {name: 'KR', label: 'South Korea'},
    {name: 'KW', label: 'Kuwait'},
    {name: 'KY', label: 'Cayman Islands'},
    {name: 'KZ', label: 'Kazakhstan'},
    {name: 'LA', label: 'Laos'},
    {name: 'LB', label: 'Lebanon'},
    {name: 'LC', label: 'Saint Lucia'},
    {name: 'LI', label: 'Liechtenstein'},
    {name: 'LK', label: 'Sri Lanka'},
    {name: 'LR', label: 'Liberia'},
    {name: 'LS', label: 'Lesotho'},
    {name: 'LT', label: 'Lithuania'},
    {name: 'LU', label: 'Luxembourg'},
    {name: 'LV', label: 'Latvia'},
    {name: 'LY', label: 'Libya'},
    {name: 'MA', label: 'Morocco'},
    {name: 'MC', label: 'Monaco'},
    {name: 'MD', label: 'Moldova'},
    {name: 'ME', label: 'Montenegro'},
    {name: 'MG', label: 'Madagascar'},
    {name: 'MH', label: 'Marshall Islands'},
    {name: 'MK', label: 'North Macedonia'},
    {name: 'ML', label: 'Mali'},
    {name: 'MM', label: 'Myanmar'},
    {name: 'MN', label: 'Mongolia'},
    {name: 'MO', label: 'Macau'},
    {name: 'MP', label: 'Northern Mariana Islands'},
    {name: 'MQ', label: 'Martinique'},
    {name: 'MR', label: 'Mauritania'},
    {name: 'MT', label: 'Malta'},
    {name: 'MU', label: 'Mauritius'},
    {name: 'MV', label: 'Maldives'},
    {name: 'MW', label: 'Malawi'},
    {name: 'MX', label: 'Mexico'},
    {name: 'MY', label: 'Malaysia'},
    {name: 'MZ', label: 'Mozambique'},
    {name: 'NA', label: 'Namibia'},
    {name: 'NC', label: 'New Caledonia'},
    {name: 'NE', label: 'Niger'},
    {name: 'NG', label: 'Nigeria'},
    {name: 'NI', label: 'Nicaragua'},
    {name: 'NL', label: 'Netherlands'},
    {name: 'NO', label: 'Norway'},
    {name: 'NP', label: 'Nepal'},
    {name: 'NR', label: 'Nauru'},
    {name: 'NU', label: 'Niue'},
    {name: 'NZ', label: 'New Zealand'},
    {name: 'OM', label: 'Oman'},
    {name: 'PA', label: 'Panama'},
    {name: 'PE', label: 'Peru'},
    {name: 'PF', label: 'French Polynesia'},
    {name: 'PG', label: 'Papua New Guinea'},
    {name: 'PH', label: 'Philippines'},
    {name: 'PK', label: 'Pakistan'},
    {name: 'PL', label: 'Poland'},
    {name: 'PR', label: 'Puerto Rico'},
    {name: 'PS', label: 'Palestine'},
    {name: 'PT', label: 'Portugal'},
    {name: 'PW', label: 'Palau'},
    {name: 'PY', label: 'Paraguay'},
    {name: 'QA', label: 'Qatar'},
    {name: 'RE', label: 'Réunion'},
    {name: 'RO', label: 'Romania'},
    {name: 'RS', label: 'Serbia'},
    {name: 'RU', label: 'Russia'},
    {name: 'RW', label: 'Rwanda'},
    {name: 'SA', label: 'Saudi Arabia'},
    {name: 'SB', label: 'Solomon Islands'},
    {name: 'SC', label: 'Seychelles'},
    {name: 'SD', label: 'Sudan'},
    {name: 'SE', label: 'Sweden'},
    {name: 'SG', label: 'Singapore'},
    {name: 'SI', label: 'Slovenia'},
    {name: 'SK', label: 'Slovakia'},
    {name: 'SL', label: 'Sierra Leone'},
    {name: 'SM', label: 'San Marino'},
    {name: 'SN', label: 'Senegal'},
    {name: 'SO', label: 'Somalia'},
    {name: 'SR', label: 'Suriname'},
    {name: 'ST', label: 'Sao Tome and Principe'},
    {name: 'SUHH', label: 'Soviet Union'},
    {name: 'SV', label: 'El Salvador'},
    {name: 'SY', label: 'Syria'},
    {name: 'SZ', label: 'Eswatini'},
    {name: 'TC', label: 'Turks and Caicos Islands'},
    {name: 'TD', label: 'Chad'},
    {name: 'TG', label: 'Togo'},
    {name: 'TH', label: 'Thailand'},
    {name: 'TJ', label: 'Tajikistan'},
    {name: 'TL', label: 'Timor-Leste'},
    {name: 'TM', label: 'Turkmenistan'},
    {name: 'TN', label: 'Tunisia'},
    {name: 'TO', label: 'Tonga'},
    {name: 'TR', label: 'Turkey'},
    {name: 'TT', label: 'Trinidad and Tobago'},
    {name: 'TW', label: 'Taiwan'},
    {name: 'TZ', label: 'Tanzania'},
    {name: 'UA', label: 'Ukraine'},
    {name: 'UG', label: 'Uganda'},
    {name: 'US', label: 'United States'},
    {name: 'UY', label: 'Uruguay'},
    {name: 'UZ', label: 'Uzbekistan'},
    {name: 'VA', label: 'Vatican City'},
    {name: 'VC', label: 'Saint Vincent and the Grenadines'},
    {name: 'VDVN', label: 'North Vietnam'},
    {name: 'VE', label: 'Venezuela'},
    {name: 'VG', label: 'British Virgin Islands'},
    {name: 'VI', label: 'U.S. Virgin Islands'},
    {name: 'VN', label: 'Vietnam'},
    {name: 'VU', label: 'Vanuatu'},
    {name: 'WS', label: 'Samoa'},
    {name: 'YE', label: 'Yemen'},
    {name: 'YUCS', label: 'Yugoslavia'},
    {name: 'ZA', label: 'South Africa'},
    {name: 'ZM', label: 'Zambia'},
    {name: 'ZRCD', label: 'Zaire'},
    {name: 'ZW', label: 'Zimbabwe'}
].sort((a, b) => a.label.localeCompare(b.label))


export const languages: Option[] = [
    {name: 'af', label: 'Afrikaans'},
    {name: 'am', label: 'Amharic'},
    {name: 'ar', label: 'Arabic'},
    {name: 'az', label: 'Azerbaijani'},
    {name: 'be', label: 'Belarusian'},
    {name: 'bg', label: 'Bulgarian'},
    {name: 'bn', label: 'Bengali'},
    {name: 'br', label: 'Breton'},
    {name: 'bs', label: 'Bosnian'},
    {name: 'ca', label: 'Catalan'},
    {name: 'cmn', label: 'Mandarin'},
    {name: 'cs', label: 'Czech'},
    {name: 'cy', label: 'Welsh'},
    {name: 'da', label: 'Danish'},
    {name: 'de', label: 'German'},
    {name: 'eka', label: 'Ekajuk'},
    {name: 'el', label: 'Greek'},
    {name: 'en', label: 'English'},
    {name: 'es', label: 'Spanish'},
    {name: 'et', label: 'Estonian'},
    {name: 'eu', label: 'Basque'},
    {name: 'fa', label: 'Persian'},
    {name: 'fi', label: 'Finnish'},
    {name: 'fr', label: 'French'},
    {name: 'fro', label: 'Old French'},
    {name: 'ga', label: 'Irish'},
    {name: 'gd', label: 'Scottish Gaelic'},
    {name: 'gl', label: 'Galician'},
    {name: 'gsw', label: 'Swiss German'},
    {name: 'gu', label: 'Gujarati'},
    {name: 'haw', label: 'Hawaiian'},
    {name: 'he', label: 'Hebrew'},
    {name: 'hi', label: 'Hindi'},
    {name: 'hil', label: 'Hiligaynon'},
    {name: 'hr', label: 'Croatian'},
    {name: 'hu', label: 'Hungarian'},
    {name: 'hy', label: 'Armenian'},
    {name: 'id', label: 'Indonesian'},
    {name: 'is', label: 'Icelandic'},
    {name: 'it', label: 'Italian'},
    {name: 'iu', label: 'Inuktitut'},
    {name: 'ja', label: 'Japanese'},
    {name: 'jsl', label: 'Japanese Sign Language'},
    {name: 'ka', label: 'Georgian'},
    {name: 'kk', label: 'Kazakh'},
    {name: 'kn', label: 'Kannada'},
    {name: 'ko', label: 'Korean'},
    {name: 'ku', label: 'Kurdish'},
    {name: 'ky', label: 'Kyrgyz'},
    {name: 'la', label: 'Latin'},
    {name: 'lb', label: 'Luxembourgish'},
    {name: 'lo', label: 'Lao'},
    {name: 'lt', label: 'Lithuanian'},
    {name: 'lv', label: 'Latvian'},
    {name: 'mi', label: 'Maori'},
    {name: 'mk', label: 'Macedonian'},
    {name: 'ml', label: 'Malayalam'},
    {name: 'mn', label: 'Mongolian'},
    {name: 'mr', label: 'Marathi'},
    {name: 'ms', label: 'Malay'},
    {name: 'my', label: 'Burmese'},
    {name: 'myv', label: 'Erzya'},
    {name: 'ne', label: 'Nepali'},
    {name: 'nl', label: 'Dutch'},
    {name: 'no', label: 'Norwegian'},
    {name: 'pa', label: 'Punjabi'},
    {name: 'pl', label: 'Polish'},
    {name: 'ps', label: 'Pashto'},
    {name: 'pt', label: 'Portuguese'},
    {name: 'qac', label: 'Qashqai'},
    {name: 'qal', label: 'Albanian (variant)'},
    {name: 'qbn', label: 'Quechua'},
    {name: 'qbo', label: 'Quechua (Bolivia)'},
    {name: 'qbp', label: 'Quechua (Peru)'},
    {name: 'rn', label: 'Kirundi'},
    {name: 'ro', label: 'Romanian'},
    {name: 'roa', label: 'Romance'},
    {name: 'ru', label: 'Russian'},
    {name: 'sd', label: 'Sindhi'},
    {name: 'sk', label: 'Slovak'},
    {name: 'sl', label: 'Slovenian'},
    {name: 'sq', label: 'Albanian'},
    {name: 'sr', label: 'Serbian'},
    {name: 'st', label: 'Sesotho'},
    {name: 'su', label: 'Sundanese'},
    {name: 'sv', label: 'Swedish'},
    {name: 'ta', label: 'Tamil'},
    {name: 'te', label: 'Telugu'},
    {name: 'tg', label: 'Tajik'},
    {name: 'th', label: 'Thai'},
    {name: 'tk', label: 'Turkmen'},
    {name: 'tl', label: 'Tagalog'},
    {name: 'tn', label: 'Tswana'},
    {name: 'tr', label: 'Turkish'},
    {name: 'uk', label: 'Ukrainian'},
    {name: 'ur', label: 'Urdu'},
    {name: 'uz', label: 'Uzbek'},
    {name: 'vi', label: 'Vietnamese'},
    {name: 'wo', label: 'Wolof'},
    {name: 'xh', label: 'Xhosa'},
    {name: 'yi', label: 'Yiddish'},
    {name: 'yue', label: 'Cantonese'},
    {name: 'zh', label: 'Chinese'},
    {name: 'zu', label: 'Zulu'}
].sort((a, b) => a.label.localeCompare(b.label))

export const types: Option[] = [
    {name: 'movie', label: 'Movie'},
    {name: 'short', label: 'Short Movie'},
    {name: 'tvEpisode', label: 'TV Episode'},
    {name: 'tvMiniSeries', label: 'TV Mini-Series'},
    {name: 'tvMovie', label: 'TV Movie'},
    {name: 'tvSeries', label: 'TV Series'},
    {name: 'tvShort', label: 'TV Short'},
    {name: 'tvSpecial', label: 'TV Special'},
    {name: 'video', label: 'Video'},
    {name: 'videoGame', label: 'Video Game'},
];
